# Generated by Django 4.2.5 on 2023-09-16 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="The level of the group from 0-8, with a letter for different groups of the same lvl  (e.g., '7B').",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The student's first name.", max_length=20
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="The student's last name.", max_length=20
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group to which the student belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "subject",
                    models.CharField(
                        help_text="The subject of the lesson.", max_length=50
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group that participated in the lesson.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.group",
                    ),
                ),
            ],
        ),
    ]
