# Generated by Django 4.2.5 on 2023-09-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="students_absent",
            field=models.ManyToManyField(blank=True, to="groups.student"),
        ),
    ]
