# Generated by Django 4.2.5 on 2023-09-20 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_lesson_students_absent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="students_absent",
            new_name="students_present",
        ),
    ]
