# Generated by Django 4.2.5 on 2023-09-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_rename_students_absent_lesson_students_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="students_absent",
            field=models.ManyToManyField(
                blank=True, related_name="lessons_absent", to="groups.student"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="students_present",
            field=models.ManyToManyField(
                blank=True, related_name="lessons_present", to="groups.student"
            ),
        ),
    ]
