# Generated by Django 4.2.5 on 2023-10-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0005_grading"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        help_text="no help text",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.student",
                    ),
                ),
            ],
        ),
    ]
