# Generated by Django 4.2.5 on 2023-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0007_singlegrade_date_delete_grading"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlegrade",
            name="description",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
