# Generated by Django 4.2.5 on 2023-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0008_singlegrade_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="opinion",
            field=models.TextField(blank=True),
        ),
    ]
