# Generated by Django 4.2.5 on 2023-11-08 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0009_student_opinion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlegrade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groups.student"
            ),
        ),
        migrations.CreateModel(
            name="PersonalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(max_length=500)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.student"
                    ),
                ),
            ],
        ),
    ]
